name: Build Shiny Docker Image and Deploy to Heroku

# Set here what events should trigger the action
on:
  push:
    branches:
      - main
      - master

jobs:

  evalue: # name the job according to the app name
    runs-on: ubuntu-latest
    # Commit message needs to contain 'deploy evalue' to trigger the job
    if: "contains(github.event.head_commit.message, 'deploy evalue')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          # app directory needs to be set relative to root of repo
          appdir: "_shinyapps/evalue"
          # this is the Heroku app name you already set up in dashboard
          heroku_app_name: evalue-main
          # secrets need to be added to the GitHub repo settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true # don't change this

#  app2: # name the job according to the app name
#    runs-on: ubuntu-latest
#    # commit message needs to contain 'deploy app2' to trigger the job
#    if: "contains(github.event.head_commit.message, 'deploy app2')"
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Build and push Docker to Heroku
#        uses: akhileshns/heroku-deploy@v3.11.10
#        with:
#          appdir: "_shinyapps/app2"
#          heroku_app_name: shiny-app2
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          usedocker: true
